name: Sync Fork

on:
  schedule:
    # يعمل تلقائياً في بداية كل ساعة
    - cron: '0 * * * *'

  # يتيح تشغيل المزامنة يدوياً من GitHub
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: hisokahunter255/collector-connect
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false
